### PR TITLE
Enforcing TLS 1.2 to be used while encrypting connections and updating few packages as required

### PR DESCRIPTION
**Pull request by abhix123**

### CODE REVIEW

**Comment by mebjas** [comment]
On a side note on this PR: @Adarsh1994 @abhix123 

I am the owner of this organisation and this repository. If you guys want I can add you as owners here.

**Comment by abhix123** [comment]
> On a side note on this PR: @Adarsh1994 @abhix123
> 
> I am the owner of this organisation and this repository. If you guys want I can add you as owners here.

@mebjas could you transfer the repo to 'msftgits' from the settings page. We are planning to move it to a new team within Azure organisation from there.

**Comment by mebjas** [comment]
Sure will do!

**Comment by mebjas** [comment]
@abhix123 I can initiate the repo transfer from my side. But someone has to accept it OBO `msgits`. I hope you guys have access to do that.

**Comment by mebjas** [comment]
So it fails with
```
You can only transfer a repository from an organization to yourself at this time
```

I'll add you as owner of this organisation and repository. You can take care of it from there.

**Pull request merged**
